[project]
name = "openalex-mcp"
version = "0.1.0"
description = "A small unofficial MCP server for the OpenAlex API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.0",
]
